### PR TITLE
Use reflection-based `PsiElement` in error reporting 

### LINKED ISSUE #428: Checker Fir
I would like to ask a question why your warnings do not work, for example, as in compose?
```Kotlin
@Poko
data class MyClass(
   val my: String
)
```
your errors are displayed after the launch!

I am asking this question purely out of curiosity, what is the reason for this. Thank you for the reply.

### PR DESCRIPTION
**Pull request by drewhamilton**
to work around compiler vs. IDE packaging issue.

I think this will address #428, but I'm having trouble verifying locally. The IDE keeps popping up the same error stacktrace, even though the `catch` is now in place. Maybe it's using some kind of caching mechanism, so I'm just going to try and merge this and see if it fixes the issue.

### CODE REVIEW

File: poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirCheckersExtension.kt [hunk 1]
```diff
@@ -78,27 +79,40 @@ internal class PokoFirCheckersExtension(
...
+        /**
+         * The compiler and the IDE use a different version of this class, so use reflection to find the available
+         * version.
+         */
+        // Adapted from https://github.com/TadeasKriz/K2PluginBase/blob/main/kotlin-plugin/src/main/kotlin/com/tadeaskriz/example/ExamplePluginErrors.kt#L8
+        private val psiElementClass by lazy {
+            try {
+                Class.forName("org.jetbrains.kotlin.com.intellij.psi.PsiElement")
+            } catch (_: ClassNotFoundException) {
+                Class.forName("com.intellij.psi.PsiElement")
```
Comment (drewhamilton) [inline poko-compiler-plugin/src/main/kotlin/dev/drewhamilton/poko/fir/PokoFirCheckersExtension.kt:91]: I swapped the order from the example, because I think the former is the one used by the compiler while the latter is used by the IDE, and I want the compiler to be faster. Not sure about this though.
